### PR TITLE
Switch from flake8/isort to ruff

### PR DESCRIPTION
**Pull request by ghickman**
We've been testing this out on job-server for some time now, it continues to be great.

### CODE REVIEW

**Comment by iaindillingham** [comment]
I'm reluctant to approve this without a team heads-up. Could you talk about why Ruff is a replacement for flake8 and isort, but isn't a replacement for black, in the next team meeting?

**Comment by ghickman** [comment]
@iaindillingham – I did, a few weeks ago!  It's very possible you weren't there though 🙂

There's a lot more detail in [the job-server PR](https://github.com/opensafely-core/job-server/pull/2839).  Hopefully that addresses your questions but very happy to talk more about it.

**Comment by iaindillingham** [comment]
Was the consensus "Yes, let's use Ruff!"?

**Comment by ghickman** [comment]
Yep, and several projects have already moved over already 😄

**Review by iaindillingham — APPROVED** [review]
In which case, ✅

**Pull request merged**
